# A very minimal "templating" structure which uses yq to:
# 1. deep-merge .wander-env[$env] into the root object,
# 2. then remove .wander-env, and finally
# 3. return the whole buffer
def wtpl_builder(env):
  def wtpl(filepath, **kwargs):
    outpath = kwargs.get('outpath')
    watch_file(filepath)

    # { "v4-bar": "docker.io/foo/bar:1.2.3", ... }
    # Broad restriction is that it must not contain ', since we're using that to enclose the json object arg.
    images = kwargs.get('images')
    if images:
      images = encode_json(images)
    else:
      images = "null"

    program = '
      ((.["wander-env"] // {})[$ENV["TILTENV"]] // {}) as $spec |
      .["wander-env"] |= empty |
      ( . * ($spec | (.containers |= empty))
      | .containers |= map(. as $container |
          ( $container * ($spec.container_overrides[$container.name] // {}) )
          | if $images[.name] != null then (.image |= $images[.name]) else . end
        )
      )
    '

    rendered = local(
      ['yq', '-y', '--images', images, program],
      quiet=True,
      echo_off=True,
      stdin=filepath,
      env={
        "TILTENV": env,
      }
    )
    if outpath:
      local(
        'cat > {outpath}'.format(outpath=outpath),
        stdin=rendered,
        quiet=True,
        echo_off=True,
      )
    else:
      # If we have not written to a file, we are expected to return the rendered result for k8s_yaml(...)
      return rendered
  return wtpl

# wtpl_helm_values
#
# The pattern of manually interpolating a helm values file and injecting that
# into the resource is a pattern we've done a few times.
#
# This accepts a lambda and strings it through.
def wtpl_helm_values_builder(env):
  wtpl = wtpl_builder(env)
  def wtpl_helm_values(name, values_src, resource=None):
    if resource == None:
      fail('wtpl_helm_values({name}, {values_src}, ...) needs a "resource" parameter'.format(name=name, values_src=values_src))
    target_dir = '/tmp/tilt-wtpl/{env}'.format(env=env)
    target = '{target_dir}/{name}.interpolated'.format(target_dir=target_dir, name=name)
    if not os.path.exists(target_dir):
      local('mkdir -p {target_dir}'.format(target_dir=shlex.quote(target_dir)))

    watch_file(values_src)
    wtpl(values_src, outpath=target)
    return resource(target)
  return wtpl_helm_values
